version: '3' #This denotes that we are using version 3 of Docker Compose
services: #This section defines all the different containers we will create.
  sonthuy: #This is the name of our Nextjs application.
    container_name: sonthuy
    build: #This specifies the location of our Dockerfile
      context: . #This specifies the location of our Dockerfile
    ports: #This is used to map the containerâ€™s ports to the host machine.
      - "${EXPORT_PORT}:3000"
